import { useCallback, useEffect, useState } from 'react'
import { playgroundApi, type PlaygroundApi } from './api/client'
import { RunPage } from './pages/RunPage'
import { Workbench } from './pages/Workbench'
import type { PlaygroundStatus } from './shared/dataset'

type Route = { name: 'home' } | { name: 'run'; analysisId: string }

export const parseRoute = (pathname: string): Route => {
  // /share/<id> is the old share URL and stays valid.
  const match = pathname.match(/^\/(?:run|share)\/([^/]+)\/?$/)
  if (!match) return { name: 'home' }
  try { return { name: 'run', analysisId: decodeURIComponent(match[1]) } } catch { return { name: 'home' } }
}

export const App = ({ api = playgroundApi }: { api?: PlaygroundApi }) => {
  const [route, setRoute] = useState<Route>(() => parseRoute(window.location.pathname))
  const [startedId, setStartedId] = useState<string>()
  const [status, setStatus] = useState<PlaygroundStatus>()

  useEffect(() => {
    const onPop = () => setRoute(parseRoute(window.location.pathname))
    window.addEventListener('popstate', onPop)
    return () => window.removeEventListener('popstate', onPop)
  }, [])

  useEffect(() => {
    let active = true
    api.status().then((next) => { if (active) setStatus(next) }).catch(() => undefined)
    return () => { active = false }
  }, [api])

  // The run gets its own URL the moment it starts, so a reload or a shared link lands on the same run.
  const openRun = useCallback((analysisId: string) => {
    setStartedId(analysisId)
    window.history.pushState(null, '', `/run/${encodeURIComponent(analysisId)}`)
    setRoute({ name: 'run', analysisId })
    window.scrollTo({ top: 0 })
  }, [])

  const simulated = status?.classifier === 'mock'

  return (
    <div className="shell">
      <header className="site-header">
        <a className="brand" href="/"><span className="brand-mark" aria-hidden="true">J</span>Jev Playground</a>
        {simulated && <span className="pill is-mock" title="No Jev key is configured, so answers are generated by a built-in stand-in.">Simulated mode</span>}
      </header>
      <main>
        {route.name === 'run'
          ? <RunPage key={route.analysisId} api={api} analysisId={route.analysisId} justStarted={startedId === route.analysisId} />
          : <Workbench api={api} status={status} onStarted={openRun} />}
      </main>
      <footer className="site-footer">
        <p>A demo for trying Jev on your own data. Answers are model output: check them before relying on them.</p>
        <p>Runs and uploaded data are public to anyone with the link.</p>
      </footer>
    </div>
  )
}
